language: objective-c
# before_install:
    # - brew update
    # - brew install xctool
script:
    - xcodebuild clean build test -workspace Example.xcworkspace -scheme ActionSheetPickerTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO

# - xctool -workspace Example.xcworkspace -scheme CoreActionSheetPicker build
# - xctool -workspace Example.xcworkspace -scheme ActionSheetPickerTests test

# xcode_workspace: Example.xcworkspace
# xcode_scheme: ActionSheetPickerTests
# xcode_sdk: iphonesimulator

notifications:
  email:
    recipients:
      - sky4winder+actionSheetPicker@gmail.com
    on_success: never # [always|never|change]
    on_failure: change # [always|never|change]